/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/todo': typeof TodoRoute
}
export interface FileRoutesByTo {
  '/todo': typeof TodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/todo': typeof TodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/todo'
  fileRoutesByTo: FileRoutesByTo
  to: '/todo'
  id: '__root__' | '/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TodoRoute: typeof TodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TodoRoute: TodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
